version: '3.8'

services:
  docs-site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9898:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Mount for development (uncomment for dev mode)
      # - .:/app
      # - /app/node_modules
      # - /app/.next
    restart: unless-stopped
    
  # Development service (alternative to production build)
  docs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9899:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    profiles:
      - dev